import { useCallback, useEffect, useRef, useState } from 'react';

interface PagefindFragment {
  url: string;
  excerpt: string;
  meta: Record<string, string>;
  filters: Record<string, string[]>;
}

interface PagefindResultStub {
  id: string;
  data: () => Promise<PagefindFragment>;
}

interface PagefindSearchResponse {
  results: PagefindResultStub[];
}

interface PagefindApi {
  search: (query: string, options?: { sort?: Record<string, 'asc' | 'desc'> }) => Promise<PagefindSearchResponse>;
  init?: () => Promise<void>;
}

declare global {
  interface Window {
    pagefind?: PagefindApi;
  }
}

const PAGE_SIZE = 3;

export default function SearchResults() {
  const [status, setStatus] = useState<'loading-index' | 'ready' | 'index-unavailable'>('loading-index');
  // Starts empty on both server and the first client render (they must match to hydrate cleanly).
  // This is a statically prerendered page, so Astro.url.searchParams is only ever evaluated at build
  // time (no request to read a query string from) — the real ?q= only exists in the browser's address
  // bar, so it's applied in the effect below, after hydration.
  const [query, setQuery] = useState('');
  const [activeTopic, setActiveTopic] = useState<string | null>(null);
  const [sort, setSort] = useState<'relevance' | 'newest'>('relevance');
  // All fragments matching the current query/sort, unfiltered by topic — resolved eagerly since the
  // whole content set is small (a few dozen answers at most). Topic counts and the active-topic
  // narrowing are both derived from this client-side, since Pagefind's own filter aggregation
  // (`search().filters` / `pagefind.filters()`) isn't scoped to the current text query.
  const [allFragments, setAllFragments] = useState<PagefindFragment[]>([]);
  const [visibleCount, setVisibleCount] = useState(PAGE_SIZE);
  const [searching, setSearching] = useState(false);
  const requestId = useRef(0);

  useEffect(() => {
    const fromUrl = new URLSearchParams(window.location.search).get('q');
    if (fromUrl) setQuery(fromUrl);
  }, []);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const pagefindEntry = '/pagefind/pagefind.js';
        const mod = (await import(/* @vite-ignore */ pagefindEntry)) as PagefindApi;
        if (cancelled) return;
        await mod.init?.();
        window.pagefind = mod;
        setStatus('ready');
      } catch {
        if (!cancelled) setStatus('index-unavailable');
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  const runSearch = useCallback(async (q: string, sortMode: 'relevance' | 'newest') => {
    if (!window.pagefind) return;
    const thisRequest = ++requestId.current;
    setSearching(true);

    const response = await window.pagefind.search(q, {
      sort: sortMode === 'newest' ? { date: 'desc' } : undefined,
    });

    if (thisRequest !== requestId.current) return; // a newer search superseded this one

    const data = await Promise.all(response.results.map((r) => r.data()));

    if (thisRequest !== requestId.current) return;

    setAllFragments(data);
    setVisibleCount(PAGE_SIZE);
    setSearching(false);
  }, []);

  useEffect(() => {
    if (status !== 'ready') return;
    runSearch(query, sort);
  }, [status, query, sort, runSearch]);

  useEffect(() => {
    setVisibleCount(PAGE_SIZE);
  }, [activeTopic]);

  const topicCounts: Record<string, number> = {};
  for (const fragment of allFragments) {
    const topic = fragment.filters.topic?.[0];
    if (topic) topicCounts[topic] = (topicCounts[topic] ?? 0) + 1;
  }
  const allTopics = Object.entries(topicCounts).sort((a, b) => b[1] - a[1]);

  const filteredFragments = activeTopic
    ? allFragments.filter((fragment) => fragment.filters.topic?.includes(activeTopic))
    : allFragments;
  const totalCount = filteredFragments.length;
  const visibleFragments = filteredFragments.slice(0, visibleCount);

  function loadMore() {
    setVisibleCount((count) => count + PAGE_SIZE);
  }

  if (status === 'index-unavailable') {
    return (
      <div className="rounded-lg border border-border bg-surface p-6 text-sm text-muted">
        Search index isn&rsquo;t available in this environment yet &mdash; it&rsquo;s generated by{' '}
        <code className="rounded bg-background px-1 py-0.5">pagefind</code> after a production build (
        <code className="rounded bg-background px-1 py-0.5">npm run build</code>), not in the dev server.
      </div>
    );
  }

  return (
    <div>
      <form
        onSubmit={(event) => event.preventDefault()}
        className="flex max-w-xl flex-col gap-2 sm:flex-row"
      >
        <div className="relative flex-1">
          <svg
            className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <circle cx="11" cy="11" r="8"></circle>
            <path d="m21 21-4.3-4.3"></path>
          </svg>
          <input
            type="search"
            value={query}
            onChange={(event) => setQuery(event.target.value)}
            placeholder="Search questions..."
            aria-label="Search questions"
            className="w-full rounded border border-border bg-white py-3 pl-9 pr-9 font-body text-base text-charcoal placeholder:text-muted focus:border-accent focus:outline-none focus:ring-1 focus:ring-accent"
          />
          {query && (
            <button
              type="button"
              onClick={() => setQuery('')}
              aria-label="Clear search"
              className="absolute right-3 top-1/2 -translate-y-1/2 text-muted hover:text-accent"
            >
              &#10005;
            </button>
          )}
        </div>
        <button
          type="submit"
          className="cursor-pointer rounded bg-accent px-6 py-3 font-semibold text-white transition-colors hover:bg-accent-dark"
        >
          Search
        </button>
      </form>

      {status === 'loading-index' ? (
        <p className="mt-4 text-sm text-muted">Loading search index...</p>
      ) : (
        <>
          <p className="mt-4 text-sm text-muted">
            {searching
              ? 'Searching...'
              : query.trim()
                ? `${totalCount} answer${totalCount === 1 ? '' : 's'} match "${query}"`
                : `${totalCount} answer${totalCount === 1 ? '' : 's'}`}
          </p>

          <div className="mt-6 grid gap-8 md:grid-cols-[220px_1fr]">
            <div>
              <p className="mb-3 font-sans text-sm font-bold text-charcoal">Filter by topic</p>
              <ul className="m-0 list-none space-y-2 p-0 text-sm">
                <li>
                  <label className="flex cursor-pointer items-center gap-2">
                    <input
                      type="checkbox"
                      checked={activeTopic === null}
                      onChange={() => setActiveTopic(null)}
                      className="accent-accent"
                    />
                    <span className={activeTopic === null ? 'font-semibold text-charcoal' : 'text-charcoal'}>
                      All topics ({allFragments.length})
                    </span>
                  </label>
                </li>
                {allTopics.map(([topic, count]) => (
                  <li key={topic}>
                    <label className="flex cursor-pointer items-center gap-2">
                      <input
                        type="checkbox"
                        checked={activeTopic === topic}
                        onChange={() => setActiveTopic(activeTopic === topic ? null : topic)}
                        className="accent-accent"
                      />
                      <span className={activeTopic === topic ? 'font-semibold text-charcoal' : 'text-charcoal'}>
                        {topic} ({count})
                      </span>
                    </label>
                  </li>
                ))}
              </ul>

              <p className="mb-2 mt-6 font-sans text-sm font-bold text-charcoal">Sort</p>
              <select
                value={sort}
                onChange={(event) => setSort(event.target.value as 'relevance' | 'newest')}
                className="w-full rounded border border-border bg-white px-2 py-1.5 text-sm text-charcoal"
              >
                <option value="relevance">Best match</option>
                <option value="newest">Newest</option>
              </select>
            </div>

            <div>
              {totalCount === 0 && !searching ? (
                <div className="flex flex-col items-center rounded-lg border border-dashed border-border p-10 text-center">
                  <span className="mb-4 flex h-12 w-12 items-center justify-center rounded-full bg-background text-muted" aria-hidden="true">
                    <svg className="h-6 w-6" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                      <circle cx="11" cy="11" r="8"></circle>
                      <path d="m21 21-4.3-4.3"></path>
                    </svg>
                  </span>
                  <p className="m-0 mb-2 font-sans text-lg font-bold text-charcoal">
                    No answers match &ldquo;{query}&rdquo;
                  </p>
                  <p className="m-0 mb-4 max-w-sm text-sm text-muted">
                    Try fewer or more general words &mdash; or just ask us. New questions are usually answered
                    and published within a day.
                  </p>
                  <div className="flex flex-wrap justify-center gap-3">
                    <a
                      href="/contact"
                      className="rounded bg-accent px-5 py-2.5 font-semibold text-white no-underline transition-colors hover:bg-accent-dark"
                    >
                      Ask this as a question
                    </a>
                    <a
                      href="/faq"
                      className="rounded border border-border px-5 py-2.5 font-semibold text-charcoal no-underline transition-colors hover:border-accent hover:text-accent"
                    >
                      Browse all topics
                    </a>
                  </div>
                </div>
              ) : (
                <div className="space-y-3">
                  {visibleFragments.map((fragment) => (
                    <ResultCard key={fragment.url} fragment={fragment} />
                  ))}
                </div>
              )}

              {visibleCount < totalCount && (
                <button
                  type="button"
                  onClick={loadMore}
                  className="mt-4 cursor-pointer text-sm font-semibold text-accent hover:underline"
                >
                  + {totalCount - visibleCount} more results...
                </button>
              )}

              <div className="mt-8 flex flex-wrap items-center justify-between gap-4 rounded-lg border border-border bg-surface px-5 py-4">
                <p className="m-0 text-sm text-charcoal">
                  Didn&rsquo;t find what you need? Ask us directly &mdash; free reply within one working day.
                </p>
                <a
                  href="/contact"
                  className="shrink-0 rounded bg-accent px-5 py-2.5 font-semibold text-white no-underline transition-colors hover:bg-accent-dark"
                >
                  Ask a Question
                </a>
              </div>
            </div>
          </div>
        </>
      )}
    </div>
  );
}

function ResultCard({ fragment }: { fragment: PagefindFragment }) {
  const [authorName, authorTitle] = (fragment.meta.author ?? '').split(', ');
  const title = fragment.meta.title ?? '';
  const topic = fragment.filters.topic?.[0];

  return (
    <a
      href={fragment.url}
      className="block rounded-lg border border-border bg-surface p-5 no-underline transition-colors hover:border-accent"
    >
      <div className="mb-2 flex flex-wrap items-center gap-2 text-[11px]">
        {topic && (
          <span className="rounded-full bg-lime-50 px-2.5 py-1 font-semibold text-green-800">
            {topic}
          </span>
        )}
        {fragment.meta.date && <span className="text-muted">Updated {fragment.meta.date}</span>}
      </div>
      <p className="m-0 mb-2 font-sans text-base font-bold text-charcoal">{title}</p>
      <p
        className="m-0 mb-2 text-sm text-muted [&_mark]:bg-transparent [&_mark]:font-semibold [&_mark]:text-accent"
        dangerouslySetInnerHTML={{ __html: fragment.excerpt }}
      />
      {authorName && (
        <p className="m-0 text-[13px] text-muted">
          {authorName}
          {authorTitle ? `, ${authorTitle}` : ''}
        </p>
      )}
    </a>
  );
}
